services:

  postgres:
    image: postgres
    container_name: PostgresDBApi
    ports:
      - "65500:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: elestio/pgadmin
    container_name: PgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "65001:80"
    
  node:
    image: skyhonnor/apiy
    container_name: NodeJSApi
    ports:
      - "9090:9090"
    
