services:

  postgres:
    image: skyhonnor/dbapiy
    container_name: PostgresDBApi
    ports:
      - "65500:5432"

  pgadmin:
    image: elestio/pgadmin
    container_name: PgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "65501:80"
    
  apijs:
    image: skyhonnor/apiy
    container_name: NodeApi
    ports:
      - "9090:9090"

  clientapijs:
    image: skyhonnor/clientapiy
    container_name: NodeClientVue
    ports:
      - "65502:80"
    
